# Generated by Django 5.1.4 on 2024-12-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='other_physical_activities',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='most_recent_antibiotic_treatment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
