# Generated by Django 5.1.4 on 2024-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_surveyresponse_other_physical_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='meat_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
