# Generated by Django 5.1.4 on 2024-12-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0003_alter_surveyresponse_meat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='other_meat_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
