# Generated by Django 5.1.4 on 2024-12-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0004_surveyresponse_other_meat_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='height_feet',
            new_name='height',
        ),
    ]
