# Generated by Django 5.1.4 on 2024-12-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0005_rename_height_feet_surveyresponse_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
