# Generated by Django 5.1.4 on 2024-12-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0007_surveyresponse_other_covid_vaccine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='heart_blood_pressure_diabetes_medication',
            field=models.CharField(choices=[('None', 'None'), ('Heart issues', 'Heart issues'), ('High BP', 'High BP'), ('Low BP', 'Low BP'), ('Diabetes', 'Diabetes'), ('Cholesterol', 'Cholesterol')], max_length=100),
        ),
    ]
