# Generated by Django 5.1.4 on 2024-12-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0008_alter_surveyresponse_heart_blood_pressure_diabetes_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='heart_blood_pressure_diabetes_medication',
            field=models.CharField(max_length=100),
        ),
    ]
