# Generated by Django 5.1.4 on 2024-12-21 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0009_alter_surveyresponse_heart_blood_pressure_diabetes_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
