# Generated by Django 5.1.4 on 2024-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0010_surveyresponse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
