# Generated by Django 5.1.4 on 2024-12-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('height_feet', models.PositiveIntegerField()),
                ('height_inches', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Athletics', 'Athletics'), ('Badminton', 'Badminton'), ('Basketball', 'Basketball'), ('Boxing', 'Boxing'), ('Cricket', 'Cricket'), ('Football', 'Football'), ('Hockey', 'Hockey'), ('Kabaddi', 'Kabaddi'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('Services Training', 'Services Training'), ('Other Sports', 'Other Sports')], max_length=30)),
                ('coach_name', models.CharField(max_length=100)),
                ('infections_diagnosed', models.CharField(choices=[('None', 'None'), ('HIV', 'HIV'), ('HBV', 'Hepatitis B virus'), ('HCV', 'Hepatitis C virus'), ('Syphilis', 'Syphilis'), ('Tuberculosis', 'Tuberculosis'), ('Cancer', 'Cancer')], max_length=20)),
                ('autoimmune_condition', models.CharField(choices=[('None', 'None'), ("Crohn's disease", "Crohn's disease"), ('Ulcerative Colitis', 'Ulcerative Colitis'), ('Rheumatoid arthritis', 'Rheumatoid arthritis'), ('Lupus', 'Lupus'), ('Multiple Sclerosis', 'Multiple Sclerosis'), ('Type 1 Diabetes', 'Type 1 Diabetes'), ('Celiac disease', 'Celiac disease'), ('Psoriasis', 'Psoriasis'), ("Graves' disease", "Graves' disease"), ("Don't Know", "Don't Know")], max_length=50)),
                ('reproductive_urinary_conditions', models.BooleanField(default=False)),
                ('cardiovascular_conditions', models.BooleanField(default=False)),
                ('nervous_bone_muscle_conditions', models.BooleanField(default=False)),
                ('sleep_disorder_medications', models.BooleanField(default=False)),
                ('allergies_asthma', models.BooleanField(default=False)),
                ('skin_conditions', models.BooleanField(default=False)),
                ('acne_history', models.BooleanField(default=False)),
                ('mental_health_conditions', models.BooleanField(default=False)),
                ('blood_transfusion', models.BooleanField(default=False)),
                ('high_risk_yellow_fever', models.BooleanField(default=False)),
                ('hospitalization_surgery', models.BooleanField(default=False)),
                ('contagious_diseases', models.BooleanField(default=False)),
                ('multi_drug_resistant_organisms', models.CharField(choices=[('None', 'None'), ('MRSA', 'MRSA'), ('VRE', 'VRE'), ('CRE', 'CRE'), ('Other', 'Other')], max_length=5)),
                ('heart_blood_pressure_diabetes_medication', models.CharField(choices=[('None', 'None'), ('Heart issues', 'Heart issues'), ('High BP', 'High BP'), ('Low BP', 'Low BP'), ('Diabetes', 'Diabetes'), ('Cholesterol', 'Cholesterol')], max_length=15)),
                ('mold_exposure', models.BooleanField(default=False)),
                ('genetic_conditions', models.BooleanField(default=False)),
                ('antibiotics_taken', models.CharField(choices=[('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('5+', '5+')], max_length=3)),
                ('most_recent_antibiotic_treatment', models.DateField()),
                ('covid_tested_positive', models.BooleanField(default=False)),
                ('hair_loss', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3)),
                ('vision_problems', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3)),
                ('blood_donation', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3)),
                ('body_fat_percentage', models.CharField(choices=[('10-12%', '10-12%'), ('15-17%', '15-17%'), ('20-22%', '20-22%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('3-4%', '3-4%'), ('6-7%', '6-7%'), ('10-12%', '10-12%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%')], max_length=15)),
                ('birth_type', models.CharField(choices=[('Normal', 'Normal'), ('C-Section', 'C-Section'), ("Don't know", "Don't know")], max_length=10)),
                ('birth_state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=30)),
                ('pin_code', models.CharField(max_length=6)),
                ('current_city', models.CharField(max_length=100)),
                ('exercise_hours_per_day', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3+', '3+')], max_length=3)),
                ('exercise_days_per_week', models.CharField(choices=[('0-1', '0-1'), ('2-3', '2-3'), ('4-5', '4-5'), ('6-7', '6-7')], max_length=3)),
                ('physical_activities', models.CharField(choices=[('Gym', 'Gym'), ('Running', 'Running'), ('Yoga', 'Yoga'), ('Sports', 'Sports'), ('Swimming', 'Swimming'), ('Cricket', 'Cricket'), ('Basketball', 'Basketball'), ('Badminton', 'Badminton'), ('Others', 'Others')], max_length=50)),
                ('proficiency_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=15)),
                ('upbringing', models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban'), ('Suburban', 'Suburban')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ("Don't know", "Don't know")], max_length=15)),
                ('smoking', models.CharField(choices=[('No', 'No'), ('Occasionally', 'Occasionally'), ('Regularly', 'Regularly'), ('Former Smoker', 'Former Smoker')], max_length=20)),
                ('alcohol_consumption', models.CharField(choices=[('No', 'No'), ('Occasionally', 'Occasionally'), ('Regularly', 'Regularly')], max_length=12)),
                ('breastfeeding', models.CharField(choices=[('Not breastfed', 'Not breastfed'), ('0-3 months', '0-3 months'), ('3-6 months', '3-6 months'), ('6+ months', '6+ months'), ("Don't know", "Don't know")], max_length=20)),
                ('bowel_movements', models.CharField(choices=[('Regular', 'Regular'), ('Irregular', 'Irregular'), ('Varies', 'Varies')], max_length=15)),
                ('bloating_acidity', models.CharField(choices=[('Rarely', 'Rarely'), ('Sometimes', 'Sometimes'), ('Often', 'Often')], max_length=10)),
                ('digestive_issues', models.CharField(choices=[('Constipation', 'Constipation'), ('Diarrhea', 'Diarrhea'), ('Neither', 'Neither')], max_length=12)),
                ('food_intolerances', models.BooleanField(default=False)),
                ('meals_per_day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], max_length=3)),
                ('snacks_per_day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6+', '6+')], max_length=3)),
                ('home_cooked_meals', models.CharField(choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3+', '3+')], max_length=8)),
                ('dairy_consumption', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('diet_type', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-vegetarian', 'Non-vegetarian'), ('Eggetarian', 'Eggetarian')], max_length=20)),
                ('meat_type', models.CharField(choices=[('Chicken', 'Chicken'), ('Fish', 'Fish'), ('Beef', 'Beef'), ('Pork', 'Pork'), ('Lamb', 'Lamb'), ('Other', 'Other')], max_length=10)),
                ('meat_frequency', models.CharField(choices=[('None', 'None'), ('1-2 times', '1-2 times'), ('3-4 times', '3-4 times'), ('5-6 times', '5-6 times'), ('Daily', 'Daily')], max_length=12)),
                ('local_cuisine', models.TextField()),
                ('medications_taken', models.BooleanField(default=False)),
                ('covid_vaccination', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('covid_vaccine', models.CharField(choices=[('Covaxin', 'Covaxin'), ('Covishield', 'Covishield'), ('Pfizer', 'Pfizer'), ('Moderna', 'Moderna'), ('Other', 'Other')], max_length=10)),
            ],
        ),
    ]
