# Generated by Django 5.1.4 on 2024-12-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='height_feet',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='height_inches',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='weight',
            field=models.CharField(max_length=10),
        ),
    ]
