# Generated by Django 5.1.4 on 2024-12-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0002_alter_surveyresponse_height_feet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='most_recent_antibiotic_treatment',
            field=models.CharField(max_length=30),
        ),
    ]
