# Generated by Django 5.1.4 on 2024-12-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0004_alter_surveyresponse_blood_donation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='height_inches',
        ),
    ]
