# Generated by Django 5.1.4 on 2024-12-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0005_remove_surveyresponse_height_inches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='autoimmune_condition',
            field=models.CharField(choices=[("Crohn's disease", "Crohn's disease"), ('Ulcerative Colitis', 'Ulcerative Colitis'), ('Rheumatoid arthritis', 'Rheumatoid arthritis'), ('Lupus', 'Lupus'), ('Multiple Sclerosis', 'Multiple Sclerosis'), ('Type 1 Diabetes', 'Type 1 Diabetes'), ('Celiac disease', 'Celiac disease'), ('Psoriasis', 'Psoriasis'), ("Graves' disease", "Graves' disease"), ("Don't Know", "Don't Know")], max_length=50),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='meat_frequency',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('1-2 times', '1-2 times'), ('3-4 times', '3-4 times'), ('5-6 times', '5-6 times'), ('Daily', 'Daily')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='meat_type',
            field=models.CharField(blank=True, choices=[('Chicken', 'Chicken'), ('Fish', 'Fish'), ('Beef', 'Beef'), ('Pork', 'Pork'), ('Lamb', 'Lamb'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
