# Generated by Django 5.1.4 on 2024-12-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0006_alter_surveyresponse_autoimmune_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='covid_vaccine',
            field=models.CharField(blank=True, choices=[('Covaxin', 'Covaxin'), ('Covishield', 'Covishield'), ('Pfizer', 'Pfizer'), ('Moderna', 'Moderna'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='description',
            field=models.CharField(choices=[('sportsperson', 'Sportsperson/Athlete'), ('army_aspirant', 'Army Aspirant'), ('nutritionist', 'Nutritionist'), ('trainer', 'Trainer'), ('coach', 'Coach'), ('Others', 'Others')], max_length=100),
        ),
    ]
