# Generated by Django 5.1.4 on 2024-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0007_alter_surveyresponse_covid_vaccine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='description',
            field=models.CharField(choices=[('sportsperson', 'Sportsperson/Athlete'), ('army_aspirant', 'Army Aspirant'), ('nutritionist', 'Nutritionist'), ('trainer', 'Trainer'), ('coach', 'Coach'), ('Other', 'Other')], max_length=100),
        ),
    ]
