# Generated by Django 5.1.4 on 2024-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0008_alter_surveyresponse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='other_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='other_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='other_multi_drug_resistant_organisms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
