# Generated by Django 5.1.4 on 2024-12-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0009_surveyresponse_other_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Chicken', 'Chicken'), ('Fish', 'Fish'), ('Beef', 'Beef'), ('Pork', 'Pork'), ('Lamb', 'Lamb'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='meat_type',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='meat_type',
            field=models.ManyToManyField(blank=True, null=True, to='survey_app.meattype'),
        ),
    ]
